---

lint_jar_path: /share/PI/malgeehe/code/lint.jar

lint_dirs:
  data: /scratch/PI/malgeehe/data/lint-spark
  sbatch: /share/PI/malgeehe/sbatch/lint
  config: /share/PI/malgeehe/config/lint

lint_application_conf: '{{ lint_dirs.config }}/application.conf'

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

# TODO: Share from spark role?
spark_dir: /share/PI/malgeehe/spark


# application.conf
lint_config:

  lint:

    gale:
      corpusDir: '{{ stacks_raw }}/gale'
      novelParquet: '{{ lint_dirs.data }}/gale.parquet'

    chicago:
      novelCSVPath: '{{ stacks_raw }}/chicago/NOVELS_METADATA.csv'
      authorCSVPath: '{{ stacks_raw }}/chicago/AUTHORS_METADATA.csv'
      textDir: '{{ stacks_raw }}/chicago/Texts'
      authorParquet: '{{ lint_dirs.data }}/chicago-authors.parquet'
      novelParquet: '{{ lint_dirs.data }}/chicago-novels.parquet'

    corpus:
      novelParquet: '{{ lint_dirs.data }}/novels.parquet'
      binCountJSON: '{{ lint_dirs.data }}/bin-counts.json'
      shuffledBinCountJSON: '{{ lint_dirs.data }}/shuffled-bin-counts.json'


lint_sbatch:

  - class: lint.jobs.Benchmark
    time: 00:10:00
    nodes: 2
    cores: 16
    mem: 4000

  - class: lint.jobs.TestConfig
    time: 00:01:00
    nodes: 1
    cores: 4
    mem: 4000

  - class: lint.jobs.LoadGale
    time: 00:30:00
    nodes: 3
    cores: 16
    mem: 64000

  - class: lint.jobs.LoadChicagoNovels
    time: 00:30:00
    nodes: 2
    cores: 16
    mem: 64000

  - class: lint.jobs.MergeCorpus
    time: 00:20:00
    nodes: 1
    cores: 16
    mem: 64000

  - class: lint.jobs.ExtBinCounts
    time: 00:20:00
    nodes: 3
    cores: 16
    mem: 64000

  - class: lint.jobs.ExtShuffledBinCounts
    time: 00:20:00
    nodes: 3
    cores: 16
    mem: 64000

  - class: lint.jobs.ExtTokenOffsets
    time: 00:20:00
    nodes: 1
    cores: 16
    mem: 64000
