---

lint_jar_path: /share/PI/malgeehe/code/lint.jar

lint_dirs:
  data: /scratch/PI/malgeehe/data/lint-spark
  sbatch: /share/PI/malgeehe/sbatch/lint
  config: /share/PI/malgeehe/config/lint

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw


# application.conf
lint_config:

  gale:
    corpus_dir: '{{ stacks_raw }}/gale'
    novel_parquet: '{{ lint_dirs.data }}/gale.parquet'

  chicago:
    novel_csv: '{{ stacks_raw }}/chicago/NOVELS_METADATA.csv'
    author_csv: '{{ stacks_raw }}/chicago/AUTHORS_METADATA.csv'
    text_dir: '{{ stacks_raw }}/chicago/Texts'


lint_sbatch:

  - class: lint.jobs.Benchmark
    time: 00:10:00
    nodes: 1
    tasks_per_node: 4
    cpus_per_task: 4
    mem: 4000

  # test
  - class: lint.jobs.LoadGale
    time: 00:10:00
    nodes: 1
    tasks_per_node: 4
    cpus_per_task: 4
    mem: 64000
