---

lint_jar_path: /share/PI/malgeehe/code/lint.jar

lint_dirs:
  data: /scratch/PI/malgeehe/data/lint-spark
  sbatch: /share/PI/malgeehe/sbatch/lint
  config: /share/PI/malgeehe/config/lint

lint_application_conf: '{{ lint_dirs.config }}/application.conf'

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

# TODO: Share from spark role?
spark_dir: /share/PI/malgeehe/spark


# application.conf
lint_config:

  gale:
    corpus_dir: '{{ stacks_raw }}/gale'
    novel_parquet: '{{ lint_dirs.data }}/gale.parquet'

  chicago:
    novel_csv: '{{ stacks_raw }}/chicago/NOVELS_METADATA.csv'
    author_csv: '{{ stacks_raw }}/chicago/AUTHORS_METADATA.csv'
    text_dir: '{{ stacks_raw }}/chicago/Texts'
    author_parquet: '{{ lint_dirs.data }}/chicago-authors.parquet'
    novel_parquet: '{{ lint_dirs.data }}/chicago-novels.parquet'


lint_sbatch:

  - class: lint.jobs.Benchmark
    time: 00:10:00
    nodes: 2
    cores: 16
    mem: 4000

  - class: lint.jobs.TestConfig
    time: 00:01:00
    nodes: 1
    cores: 4
    mem: 4000

  - class: lint.jobs.LoadGale
    time: 00:30:00
    nodes: 3
    cores: 16
    mem: 64000

  - class: lint.jobs.LoadChicagoNovels
    time: 00:30:00
    nodes: 2
    cores: 16
    mem: 64000

  # test
  - class: lint.jobs.MergeCorpus
    time: 00:10:00
    nodes: 1
    cores: 16
    mem: 64000
