---

lint_repo: git@github.com:davidmcclure/literary-interior.git
lint_branch: master

lint_dirs:
  code: /share/PI/malgeehe/code/lint
  config: /share/PI/malgeehe/config/lint
  data: /scratch/PI/malgeehe/data/lint
  sbatch: /share/PI/malgeehe/sbatch/lint

htrc_data: /scratch/PI/malgeehe/data/htrc

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

# ****

lint_chars: '{{ lint_dirs.data }}/results/chars'
lint_tokens: '{{ lint_dirs.data }}/results/tokens'

lint_config:

  htrc:
    features: '{{ htrc_data }}'
    manifest: '{{ htrc_data }}/pd-basic-file-listing.txt'

  gail: '{{ stacks_raw }}/gail-amfic'

  chicago: '{{ stacks_raw }}/chicago'

  results:

    chars:
      htrc: '{{ lint_chars }}/htrc'
      chicago: '{{ lint_chars }}/chicago'
      gail: '{{ lint_chars }}/gail'

    tokens:
      htrc: '{{ lint_tokens }}/htrc'
      chicago: '{{ lint_tokens }}/chicago'
      gail: '{{ lint_tokens }}/gail'

  database: '{{ lint_dirs.data }}/lint.db'

# ****

lint_sbatch_mpi:

  - name: ext-chicago-tokens
    time: 02:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: ext-chicago-chars
    time: 02:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: ext-gail-tokens
    time: 02:00:00
    nodes: 3
    tasks: 16
    mem: 64000

  - name: ext-gail-chars
    time: 02:00:00
    nodes: 3
    tasks: 16
    mem: 64000

# ****

lint_sbatch:

  - name: gather-chicago-tokens
    time: 02:00:00
    nodes: 1
    tasks: 3
    mem: 12000

  - name: gather-chicago-chars
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000

  - name: gather-gail-tokens
    time: 05:00:00
    nodes: 1
    tasks: 3
    mem: 12000

  - name: gather-gail-chars
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000
