---

lint_repo: git@github.com:davidmcclure/literary-interior.git
lint_branch: master

lint_dirs:
  code: /share/PI/malgeehe/code/lint
  config: /share/PI/malgeehe/config/lint
  data: /scratch/PI/malgeehe/data/lint
  sbatch: /share/PI/malgeehe/sbatch/lint

lint_result_dirs:
  htrc: '{{ lint_dirs.data }}/results/htrc'
  chicago: '{{ lint_dirs.data }}/results/chicago'
  gail: '{{ lint_dirs.data }}/results/gail'

lint_db: '{{ lint_dirs.data }}/lint.db'

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

htrc_data: /scratch/PI/malgeehe/data/htrc

lint_sbatch_mpi:

  - name: extract-chicago
    time: 02:00:00
    nodes: 2
    tasks: 16
    mem: 64000

lint_sbatch:

  - name: gather-chicago
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000
