---

lint_repo: git@github.com:davidmcclure/literary-interior.git
lint_branch: master

lint_dirs:
  code: /share/PI/malgeehe/code/lint
  config: /share/PI/malgeehe/config/lint
  data: /scratch/PI/malgeehe/data/lint
  sbatch: /share/PI/malgeehe/sbatch/lint

# TODO: Simplify?

lint_results:
  tokens: '{{ lint_dirs.data }}/results/tokens'
  chars: '{{ lint_dirs.data }}/results/chars'

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

htrc_data: /scratch/PI/malgeehe/data/htrc


lint_config:

  htrc:
    features: '{{ htrc_data }}'
    manifest: '{{ htrc_data }}/pd-basic-file-listing.txt'

  gail: '{{ stacks_raw }}/gail-amfic'

  chicago: '{{ stacks_raw }}/chicago'

  results:

    tokens:
      htrc: '{{ lint_results.tokens }}/htrc'
      chicago: '{{ lint_results.tokens }}/chicago'
      gail: '{{ lint_results.tokens }}/gail'

    chars:
      htrc: '{{ lint_results.chars }}/htrc'
      chicago: '{{ lint_results.chars }}/chicago'
      gail: '{{ lint_results.chars }}/gail'

  database: '{{ lint_dirs.data }}/lint.db'


lint_sbatch_mpi:

  - name: ext-chicago-tokens
    time: 02:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: ext-chicago-chars
    time: 02:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: ext-gail-tokens
    time: 02:00:00
    nodes: 3
    tasks: 16
    mem: 64000

  - name: ext-gail-chars
    time: 02:00:00
    nodes: 3
    tasks: 16
    mem: 64000


lint_sbatch:

  - name: gather-chicago-tokens
    time: 02:00:00
    nodes: 1
    tasks: 3
    mem: 12000

  - name: gather-chicago-chars
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000

  - name: gather-gail-tokens
    time: 05:00:00
    nodes: 1
    tasks: 3
    mem: 12000

  - name: gather-gail-chars
    time: 01:00:00
    nodes: 1
    tasks: 1
    mem: 4000
