---

lint_repo: git@github.com:davidmcclure/literary-interior.git
lint_branch: master

lint_dirs:
  code: /share/PI/malgeehe/code/lint
  config: /share/PI/malgeehe/config/lint
  data: /scratch/PI/malgeehe/data/lint
  sbatch: /share/PI/malgeehe/sbatch/lint

stacks_raw: /scratch/PI/malgeehe/data/stacks/raw

htrc_data: /scratch/PI/malgeehe/data/htrc

# ****

lint_config:

  gail: '{{ stacks_raw }}/gail-amfic'

  chicago: '{{ stacks_raw }}/chicago'

  results:
    texts: '{{ lint_dirs.data}}/results/texts'
    buckets: '{{ lint_dirs.data}}/results/buckets'
    tokens: '{{ lint_dirs.data}}/results/tokens'

  database: '{{ lint_dirs.data }}/lint.db'

# ****

lint_sbatch_mpi:

  - name: ext-chicago-texts
    time: 00:10:00
    nodes: 1
    tasks: 1
    mem: 4000

  - name: ext-gail-texts
    time: 01:00:00
    nodes: 2
    tasks: 16
    mem: 64000

  - name: ext-buckets
    time: 03:00:00
    nodes: 3
    tasks: 16
    mem: 64000

lint_sbatch:

  - name: gather-texts
    time: 00:40:00
    nodes: 1
    tasks: 1
    mem: 4000

  - name: gather-buckets
    time: 05:00:00
    nodes: 1
    tasks: 8
    mem: 32000
