---

- name: Create project directories
  file:
    path: '{{ item.value }}'
    state: directory
  with_dict: '{{ lint_dirs }}'

- name: Create result directories
  file:
    path: '{{ item.value }}'
    state: directory
  with_dict: '{{ lint_result_dirs }}'

- name: Pull the source code
  git:
    repo: '{{ lint_repo }}'
    version: '{{ lint_branch }}'
    dest: '{{ lint_dirs.code }}'
    accept_hostkey: yes

- name: Push the config files
  template:
    src: lint/{{ item }}.yml.j2
    dest: '{{ lint_dirs.config }}/{{ item }}.yml'
  with_items:
    - lint

- name: Install the package
  command: bin/setup-sherlock
  args:
    chdir: '{{ lint_dirs.code }}'

- name: Configure .bashrc
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/.bashrc
    line: export LINT_CONFIG={{ lint_dirs.config }}

- name: Push MPI sbatch configs
  template:
    src: sbatch-mpi.j2
    dest: '{{ lint_dirs.sbatch }}/{{ item.name }}.sbatch'
  with_items: '{{ lint_sbatch_mpi }}'

- name: Push single-threaded sbatch configs
  template:
    src: sbatch.j2
    dest: '{{ lint_dirs.sbatch }}/{{ item.name }}.sbatch'
  with_items: '{{ lint_sbatch }}'
